### PR TITLE
fix: Change to using is-builtin-module

### LINKED ISSUE #137: [file-extension-in-import] Does not work with node version 16.0.0 - 16.16.0
### Environment

Node version: 16.16.0
eslint-plugin-n version: 16.3.0

With the following config:
```javascript
"n/file-extension-in-import": ["error", "always"]
```

I see the error,
```
isBuiltin is not a function
```

`isBuiltin` was added to node in version v16.17.0

### What rule do you want to report?

n/file-extension-in-import

Proposal:
Docs can be updated to reflect the requirement for node version

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by scagood**
fixes #137

### CODE REVIEW

**Comment by scagood** [comment]
I have added v16.0.0 to our CI run as I have made this mistake one too many times :grimacing:

**Review by aladdin-add — APPROVED** [review]
