### ISSUE TITLE
[file-extension-in-import] Does not work with node version 16.0.0 - 16.16.0

### ISSUE THREAD

**Issue by venkat-kaluva** [eslint-community/eslint-plugin-n#137]
### Environment

Node version: 16.16.0
eslint-plugin-n version: 16.3.0

With the following config:
```javascript
"n/file-extension-in-import": ["error", "always"]
```

I see the error,
```
isBuiltin is not a function
```

`isBuiltin` was added to node in version v16.17.0

### What rule do you want to report?

n/file-extension-in-import

Proposal:
Docs can be updated to reflect the requirement for node version

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by scagood** [comment]
Sorry about this, I will get on it this afternoon!

**Comment by aladdin-add** [comment]
yes, it should be fixed - node.js v16 is still supported.

**Comment by cheezone** [comment]
@scagood  This problem has appeared again. Does this library not support node 16.0.*?

**Comment by scagood** [comment]
As of version 17, we have dropped support for node 16, yes.

The current minimum version is 18.18.0

https://github.com/eslint-community/eslint-plugin-n/commit/41ceed7ad17e42f3074e664081f69639d0fb4322
