### PR TITLE
fix: eslint 7.0 support

### LINKED ISSUE #155: Bug: The readme says this supports ESLint >=7.0.0, but ruleContext.physicalFilename doesn't exist in version 7.15.0 on my machine
Bug: The readme says this supports ESLint >=7.0.0, but ruleContext.physicalFilename (used in is-typescript.js) doesn't exist in eslint version 7.15.0 on my machine

### Environment

Node version: 18.17.0
npm version: 9.6.7
ESLint version: 7.15.0
eslint-plugin-n version: 16.6.0
Operating System: Windows 11

### What rule do you want to report?

n/no-missing-import

### Link to Minimal Reproducible Example

playground apparently doesn't work with eslint 7.15.0

### What did you expect to happen?

I expected eslint version 7.15.0 to work, but instead eslint-plugin-n throws TypeError "context.getPhysicalFilename is not a function"

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by aladdin-add**
fixes #155

### CODE REVIEW

**Review by scagood — APPROVED** [review]

**Comment by scagood** [comment]
It looks like we may need to bump the lowest eslint version to `^7.5.0` :thinking:
```
npm WARN Could not resolve dependency:
npm WARN peer eslint@">=8" from eslint-plugin-es-x@7.5.0
npm WARN node_modules/eslint-plugin-es-x
npm WARN   eslint-plugin-es-x@"^7.5.0" from the root project
```

**Comment by aladdin-add** [comment]
> It looks like we may need to bump the lowest eslint version to ^7.5.0 🤔

it could be a breaking to bump the required eslint version. The change is just a bugfix - regardless, the eslint v7 support will be likely dropped in v17.

**Comment by SlyryD** [comment]
> > It looks like we may need to bump the lowest eslint version to ^7.5.0 🤔
> 
> it could be a breaking to bump the required eslint version. The change is just a bugfix - regardless, the eslint v7 support will be likely dropped in v17.

What's the reason for dropping eslint v7 support in the next eslint-plugin-n release?

**Comment by aladdin-add** [comment]
When we release major releases, we will consider dropping support for some of the older eslint, and will just support the latest 2 major versions (as we have done in the past).

Do you have any concerns?🤔
