### ISSUE TITLE
Bug: The readme says this supports ESLint >=7.0.0, but ruleContext.physicalFilename doesn't exist in version 7.15.0 on my machine

### ISSUE THREAD

**Issue by SlyryD** [eslint-community/eslint-plugin-n#155]
Bug: The readme says this supports ESLint >=7.0.0, but ruleContext.physicalFilename (used in is-typescript.js) doesn't exist in eslint version 7.15.0 on my machine

### Environment

Node version: 18.17.0
npm version: 9.6.7
ESLint version: 7.15.0
eslint-plugin-n version: 16.6.0
Operating System: Windows 11

### What rule do you want to report?

n/no-missing-import

### Link to Minimal Reproducible Example

playground apparently doesn't work with eslint 7.15.0

### What did you expect to happen?

I expected eslint version 7.15.0 to work, but instead eslint-plugin-n throws TypeError "context.getPhysicalFilename is not a function"

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by SlyryD** [comment]
I got the same issue on eslint 7.32.0, so I expect the readme just needs to be updated to say this project Requires ESLint >=8.0.0

**Comment by SlyryD** [comment]
It looks like it was added in eslint 7.28.0
